final List<String> frasesMotivacionais = [
  "Acredite em você mesmo e em todo o seu potencial.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "A única maneira de fazer um excelente trabalho é amar o que você faz.",
  "Grandes coisas nunca vêm de zonas de conforto.",
  "A persistência é o caminho do êxito.",
  "Não espere por oportunidades, crie-as.",
  "A jornada de mil milhas começa com um único passo.",
  "O fracasso é apenas a oportunidade de começar de novo com mais inteligência.",
  "Acredite que você pode e você já está no meio do caminho.",
  "A motivação é o que te faz começar, o hábito é o que te mantém em frente.",
  "A vida é 10% o que acontece com você e 90% como você reage a isso.",
  "O sucesso não é final, o fracasso não é fatal: é a coragem de continuar que conta.",
  "Você é mais forte do que pensa, mais capaz do que imagina.",
  "Se você pode sonhar, você pode realizar.",
  "Não se trata de ser o melhor. Trata-se de ser melhor do que você era ontem.",
  "O futuro pertence àqueles que acreditam na beleza de seus sonhos.",
  "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
  "Acredite em milagres, mas não dependa deles.",
  "Você é o único responsável por sua felicidade.",
  "Não deixe que o medo de perder seja maior que a vontade de ganhar.",
  "A melhor maneira de prever o futuro é criá-lo.",
  "Não pare quando estiver cansado. Pare quando tiver terminado.",
  "O único limite para a nossa realização de amanhã são as nossas dúvidas de hoje.",
  "Faça de cada dia a sua obra-prima.",
  "A força não vem da capacidade física, mas de uma vontade indomável.",
  "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.",
  "Você nunca sabe a força que tem até que a sua única alternativa é ser forte.",
  "A maior glória em viver não está em nunca cair, mas em nos levantar toda vez que caímos.",
  "A única maneira de fazer um bom trabalho é amar o que você faz.",
  "Nunca é tarde para ser o que você poderia ter sido."
];
